// AUTO-GENERATED — do not edit manually
// Updated: 2026-07-24 via fantasypoints.com Best Ball ADP (Underdog)
// Re-run: node scripts/update-adp.js
const RAW = [
  ["Jahmyr Gibbs","RB","DET",1.1],["Bijan Robinson","RB","ATL",2],["Ja'Marr Chase","WR","CIN",3.1],
  ["Puka Nacua","WR","LAR",4],["Jaxon Smith-Njigba","WR","SEA",5.4],["Christian McCaffrey","RB","SF",6.4],
  ["Amon-Ra St. Brown","WR","DET",7.2],["Jonathan Taylor","RB","IND",7.9],["CeeDee Lamb","WR","DAL",9.6],
  ["Justin Jefferson","WR","MIN",10],["Ashton Jeanty","RB","LV",11.2],["James Cook","RB","BUF",11.6],
  ["Saquon Barkley","RB","PHI",13.4],["Omarion Hampton","RB","LAC",14.5],["Kenneth Walker","RB","KC",15.9],
  ["Chase Brown","RB","CIN",16.4],["Devon Achane","RB","MIA",17.3],["Derrick Henry","RB","BAL",17.8],
  ["A.J. Brown","WR","NE",18.2],["Drake London","WR","ATL",19.8],["Brock Bowers","TE","LV",20.6],
  ["Nico Collins","WR","HOU",22.3],["George Pickens","WR","DAL",23.5],["Jeremiyah Love","RB","ARI",24.4],
  ["Rashee Rice","WR","KC",25.3],["DeVonta Smith","WR","PHI",26.3],["Breece Hall","RB","NYJ",28],
  ["Trey McBride","TE","ARI",28.7],["Chris Olave","WR","NO",29.7],["Zay Flowers","WR","BAL",30.4],
  ["Kyren Williams","RB","LAR",31.3],["Tee Higgins","WR","CIN",32.4],["Emeka Egbuka","WR","TB",32.6],
  ["Ladd McConkey","WR","LAC",35.3],["Josh Allen","QB","BUF",35.5],["Travis Etienne Jr.","RB","NO",35.7],
  ["Javonte Williams","RB","DAL",36.3],["Malik Nabers","WR","NYG",38.3],["Tetairoa McMillan","WR","CAR",38.7],
  ["Garrett Wilson","WR","NYJ",39.3],["Josh Jacobs","RB","GB",40.3],["Jaylen Waddle","WR","DEN",41.9],
  ["Cam Skattebo","RB","NYG",43.6],["Terry McLaurin","WR","WAS",44.3],["Luther Burden","WR","CHI",44.4],
  ["Mike Evans","WR","SF",45.9],["Colston Loveland","TE","CHI",46.9],["David Montgomery","RB","HOU",47.8],
  ["Davante Adams","WR","LAR",49.7],["Jameson Williams","WR","DET",50.4],["D'Andre Swift","RB","CHI",50.5],
  ["TreVeyon Henderson","RB","NE",52.5],["Quinshon Judkins","RB","CLE",53.8],["Mar'Keise Irving","RB","TB",54.4],
  ["Lamar Jackson","QB","BAL",55.3],["Bhayshul Tuten","RB","JAX",55.8],["D.J. Moore","WR","BUF",56.5],
  ["Christian Watson","WR","GB",56.7],["Carnell Tate","WR","TEN",58.4],["Rome Odunze","WR","CHI",60.1],
  ["Brian Thomas","WR","JAX",61.2],["Jadarian Price","RB","SEA",62.7],["Jordyn Tyson","WR","NO",63.6],
  ["Tyler Warren","TE","IND",64.5],["Drake Maye","QB","NE",66.2],["Jayden Daniels","QB","WAS",67.1],
  ["Parker Washington","WR","JAX",67.1],["Joe Burrow","QB","CIN",67.7],["Marvin Harrison Jr.","WR","ARI",68],
  ["Caleb Williams","QB","CHI",71.6],["Jalen Hurts","QB","PHI",71.8],["Tony Pollard","RB","TEN",72.4],
  ["Makai Lemon","WR","PHI",73.2],["Jaylen Warren","RB","PIT",73.6],["Quentin Johnston","WR","LAC",74.7],
  ["Rhamondre Stevenson","RB","NE",76.5],["DK Metcalf","WR","PIT",77.2],["Chuba Hubbard","RB","CAR",77.6],
  ["Alec Pierce","WR","IND",79.9],["Dak Prescott","QB","DAL",80.9],["Justin Herbert","QB","LAC",82],
  ["Tucker Kraft","TE","GB",82.4],["Courtland Sutton","WR","DEN",83],["Jayden Reed","WR","GB",84.2],
  ["Trevor Lawrence","QB","JAX",85.7],["RJ Harvey","RB","DEN",86.3],["Rico Dowdle","RB","PIT",87],
  ["Chris Godwin","WR","TB",87.2],["Jordan Addison","WR","MIN",89],["Josh Downs","WR","IND",90.2],
  ["Blake Corum","RB","LAR",91.6],["Patrick Mahomes","QB","KC",93.1],["Kyle Monangai","RB","CHI",93.5],
  ["Xavier Worthy","WR","KC",94.4],["Sam LaPorta","TE","DET",95.2],["Brock Purdy","QB","SF",96.2],
  ["Ricky Pearsall","WR","SF",96.5],["J.K. Dobbins","RB","DEN",98.3],["Michael Pittman Jr.","WR","PIT",99.3],
  ["Michael Wilson","WR","ARI",100.5],["Jonathon Brooks","RB","CAR",101.5],["Jaxson Dart","QB","NYG",101.9],
  ["Harold Fannin","TE","CLE",104.4],["Kyle Pitts","TE","ATL",105],["Matthew Stafford","QB","LAR",106.1],
  ["Jakobi Meyers","WR","JAX",106.5],["Bo Nix","QB","DEN",107],["Kenneth Gainwell","RB","TB",107.6],
  ["Rachaad White","RB","WAS",108.3],["Jared Goff","QB","DET",109.7],["Matthew Golden","WR","GB",110.3],
  ["Kyler Murray","QB","MIN",111.4],["Jordan Love","QB","GB",112.4],["George Kittle","TE","SF",113.2],
  ["Wan'Dale Robinson","WR","TEN",113.8],["Jordan Mason","RB","MIN",114.5],["Romeo Doubs","WR","NE",116.9],
  ["Baker Mayfield","QB","TB",118.4],["KC Concepcion","WR","CLE",118.4],["Aaron Jones","RB","MIN",120.2],
  ["Travis Kelce","TE","KC",121.3],["Jacory Croskey-Merritt","RB","WAS",121.7],["Tyler Shough","QB","NO",123.6],
  ["Jayden Higgins","WR","HOU",124.1],["Mark Andrews","TE","BAL",125.7],["Khalil Shakir","WR","BUF",126.9],
  ["Chris Rodriguez Jr.","RB","JAX",127.4],["Dalton Kincaid","TE","BUF",128.2],["Jake Ferguson","TE","DAL",129.7],
  ["Isaiah Likely","TE","NYG",130],["Jalen Coker","WR","CAR",131],["Rashid Shaheed","WR","SEA",131.1],
  ["Tyrone Tracy","RB","NYG",133.6],["Malik Willis","QB","MIA",133.9],["Stefon Diggs","WR","FA",134.3],
  ["Dallas Goedert","TE","PHI",135.2],["Keaton Mitchell","RB","LAC",137.1],["Cameron Ward","QB","TEN",139.6],
  ["Chig Okonkwo","TE","WAS",140.4],["Sam Darnold","QB","SEA",141],["Travis Hunter","WR","JAX",142],
  ["CJ Stroud","QB","HOU",142.7],["Woody Marks","RB","HOU",142.8],["Omar Cooper","WR","NYJ",143.9],
  ["Jalen McMillan","WR","TB",145.1],["Daniel Jones","QB","IND",146.5],["Jalen Nailor","WR","LV",147.6],
  ["Isiah Pacheco","RB","DET",148.8],["Oronde Gadsden","TE","LAC",149.3],["Brenton Strange","TE","JAX",150.7],
  ["Hunter Henry","TE","NE",151.5],["Jauan Jennings","WR","MIN",152.8],["Tre Tucker","WR","LV",153.3],
  ["Tyjae Spears","RB","TEN",153.4],["Denzel Boston","WR","CLE",155],["Jonah Coleman","RB","DEN",156.3],
  ["Juwan Johnson","TE","NO",156.6],["Bryce Young","QB","CAR",158.3],["Zach Charbonnet","RB","SEA",159.8],
  ["Ryan Flournoy","WR","DAL",160.5],["Kenyon Sadiq","TE","NYJ",160.9],["Tyler Allgeier","RB","ARI",162.5],
  ["Tank Bigsby","RB","PHI",163.4],["Deebo Samuel","WR","FA",164.4],["Tre Harris","WR","LAC",166.4],
  ["Isaac TeSlaa","WR","DET",166.7],["Alvin Kamara","RB","NO",168.1],["Dalton Schultz","TE","HOU",168.4],
  ["T.J. Hockenson","TE","MIN",169],["Brian Robinson","RB","ATL",171.5],["Adonai Mitchell","WR","NYJ",172.1],
  ["De'Zhaun Stribling","WR","SF",172.4],["Dylan Sampson","RB","CLE",172.7],["Fernando Mendoza","QB","LV",174.6],
  ["AJ Barner","TE","SEA",174.7],["Antonio Williams","WR","WAS",174.8],["Aaron Rodgers","QB","PIT",177.4],
  ["Greg Dulcich","TE","MIA",177.7],["Jerry Jeudy","WR","CLE",179.5],["Gunnar Helm","TE","TEN",180.9],
  ["Zachariah Branch","WR","ATL",181.7],["Malik Washington","WR","MIA",183.2],["Geno Smith","QB","NYJ",184.8],
  ["Sean Tucker","RB","TB",184.9],["Cade Otton","TE","TB",186.9],["Germie Bernard","WR","PIT",187],
  ["Terrance Ferguson","TE","LAR",188.2],["Calvin Ridley","WR","TEN",188.7],["Dontayvion Wicks","WR","PHI",190.5],
  ["Emmett Johnson","RB","KC",190.8],["Ray Davis","RB","BUF",191.8],["Pat Freiermuth","TE","PIT",192.6],
  ["Jaydon Blue","RB","DAL",194.3],["Tank Dell","WR","HOU",195.1],["Marshawn Lloyd","RB","GB",196.5],
  ["Jacoby Brissett","QB","ARI",197.1],["Darnell Mooney","WR","NYG",197.4],["Mike Washington","RB","LV",198.2],
  ["Ted Hurst","WR","TB",202],["Kaytron Allen","RB","WAS",202.2],["Pat Bryant","WR","DEN",204.5],
  ["Mike Gesicki","TE","CIN",204.7],["Braelon Allen","RB","NYJ",205.2],["Elijah Sarratt","WR","BAL",205.5],
  ["Cooper Kupp","WR","SEA",206.8],["Tua Tagovailoa","QB","ATL",207.1],["Keon Coleman","WR","BUF",208.1],
  ["Jaylin Noel","WR","HOU",209],["Eli Stowers","TE","PHI",209],["Nicholas Singleton","RB","TEN",209],
  ["Rashod Bateman","WR","BAL",209.5],["Colby Parkinson","TE","LAR",210.5],["Jordan James","RB","SF",210.7],
  ["Kayshon Boutte","WR","NE",212],["Tyquan Thornton","WR","KC",212],["George Holani","RB","SEA",212.1],
  ["David Njoku","TE","LAC",212.6],["Evan Engram","TE","DEN",212.6],["Troy Franklin","WR","DEN",212.7],
  ["Keenan Allen","WR","FA",213],["Demond Claiborne","RB","MIN",213.2],["Chris Brazzell","WR","CAR",213.3],
  ["Brandon Aiyuk","WR","SF",213.7],["Malachi Fields","WR","NYG",213.7],["Christian Kirk","WR","SF",213.8],
  ["Shedeur Sanders","QB","CLE",213.8],["Justice Hill","RB","BAL",213.9],["Kimani Vidal","RB","LAC",214.4],
  ["Kaelon Black","RB","SF",214.4],["Tyreek Hill","WR","FA",214.5],["Chris Bell","WR","MIA",214.6],
  ["Darnell Washington","TE","PIT",214.7],["Tory Horton","WR","SEA",214.8],["Deshaun Watson","QB","CLE",215],
  ["Michael Mayer","TE","LV",215],["Michael Penix Jr.","QB","ATL",215],["Devaughn Vele","WR","NO",215],
  ["Kirk Cousins","QB","LV",215.1],["Samaje Perine","RB","CIN",215.1],["James Conner","RB","ARI",215.2],
  ["Andrei Iosivas","WR","CIN",215.2],["Jack Bech","WR","LV",215.2],["DJ Giddens","RB","IND",215.2],
  ["Ja'Kobi Lane","WR","BAL",215.2],["Jalen Tolbert","WR","MIA",215.3],["Skyler Bell","WR","BUF",215.3],
  ["Darius Slayton","WR","NYG",215.4],["Jake Tonges","TE","SF",215.4],["Caleb Douglas","WR","MIA",215.4],
  ["Charlie Kolar","TE","LAC",215.5],["Theo Johnson","TE","NYG",215.5],["Emanuel Wilson","RB","SEA",215.6],
  ["Jaylen Wright","RB","MIA",215.6],["Ja'Tavion Sanders","TE","CAR",215.7],["Carson Beck","QB","ARI",215.7],
  ["LeQuint Allen","RB","JAX",215.7],["Ty Johnson","RB","BUF",215.8],["Dawson Knox","TE","BUF",215.8],
  ["Chimere Dike","WR","TEN",215.8],["Elijah Arroyo","TE","SEA",215.8],["Kalif Raymond","WR","CHI",215.9],
  ["Kendrick Bourne","WR","ARI",215.9],["Hollywood Brown","WR","PHI",215.9],["Najee Harris","RB","FA",215.9],
  ["Cole Kmet","TE","CHI",215.9],["Justin Fields","QB","KC",215.9],["Mac Jones","QB","SF",215.9],
  ["Tutu Atwell","WR","MIA",215.9],["Treylon Burks","WR","WAS",215.9],["Marvin Mims","WR","DEN",215.9],
  ["Christopher Brooks","RB","GB",215.9],["Malik Davis","RB","DAL",215.9],["KaVontae Turpin","WR","DAL",215.9],
  ["Emari Demercado","RB","KC",215.9],["J.J. McCarthy","QB","MIN",215.9],["Devontez Walker","WR","BAL",215.9],
  ["Xavier Legette","WR","CAR",215.9],["Isaiah Davis","RB","NYJ",215.9],["Erick All","TE","CIN",215.9],
  ["Kyle Williams","WR","NE",215.9],["Tez Johnson","WR","TB",215.9],["Tahj Brooks","RB","CIN",215.9],
  ["Ollie Gordon","RB","MIA",215.9],["Mason Taylor","TE","NYJ",215.9],["Elic Ayomanor","WR","TEN",215.9],
  ["Oscar Delp","TE","NO",215.9],["Isaiah Bond","WR","CLE",215.9],["Savion Williams","WR","GB",215.9],
  ["Adam Randall","WR","BAL",215.9],["Brenen Thompson","WR","LAC",215.9],["Justin Joly","TE","DEN",215.9],
  ["Bryce Lance","WR","NO",215.9],["Eli Raridon","TE","NE",215.9],["Joe Flacco","QB","CIN",216],
  ["Tyrod Taylor","QB","GB",216],["Andy Dalton","QB","PHI",216],["Teddy Bridgewater","QB","DET",216],
  ["Jameis Winston","QB","NYG",216],["Marcus Mariota","QB","WAS",216],["Darren Waller","TE","FA",216],
  ["Mitchell Trubisky","QB","TEN",216],["Joe Mixon","RB","FA",216],["Kareem Hunt","RB","FA",216],
  ["Jonnu Smith","TE","FA",216],["Nick Chubb","RB","HOU",216],["Jordan Akins","TE","FA",216],
  ["Kyle Allen","QB","BUF",216],["Noah Fant","TE","NO",216],["Drew Lock","QB","SEA",216],
  ["Gardner Minshew II","QB","ARI",216],["Josh Oliver","TE","MIN",216],["Devin Singletary","RB","NYG",216],
  ["Jarrett Stidham","QB","DEN",216],["Noah Gray","TE","KC",216],["Daniel Bellinger","TE","TEN",216],
  ["Julius Chestnut","RB","TEN",216],["Anthony Richardson","QB","IND",216],["Tanner McKee","QB","PHI",216],
  ["Luke Musgrave","TE","GB",216],["Payne Durham","TE","TB",216],["Tyson Bagent","QB","CHI",216],
  ["Trey Benson","RB","ARI",216],["Tommy DeVito","QB","NE",216],["Jawhar Jordan","RB","HOU",216],
  ["Riley Leonard","QB","IND",216],["Rasheen Ali","RB","BAL",216],["Isaac Guerendo","RB","SF",216],
  ["Will Shipley","RB","PHI",216],["Jordan Whittington","WR","LAR",216],["Mitchell Evans","TE","CAR",216],
  ["Jalen Milroe","QB","SEA",216],["Will Howard","QB","PIT",216],["Devin Neal","RB","NO",216],
  ["Brashard Smith","RB","KC",216],["Trevor Etienne","RB","CAR",216],["Phil Mafah","RB","DAL",216],
  ["Damien Martinez","RB","GB",216],["Kaleb Johnson","RB","PIT",216],["Quinn Ewers","QB","MIA",216],
  ["Ty Simpson","QB","LAR",216],["Max Klare","TE","LAR",216],["Robert Henry","RB","WAS",216],
];

const BYE_WEEKS = {
  "ARI": 11,
  "ATL": 12,
  "BAL": 14,
  "BUF": 12,
  "CAR": 11,
  "CHI": 7,
  "CIN": 12,
  "CLE": 10,
  "DAL": 7,
  "DEN": 9,
  "DET": 5,
  "GB": 12,
  "HOU": 14,
  "IND": 14,
  "JAX": 12,
  "KC": 10,
  "LAC": 5,
  "LAR": 6,
  "LV": 10,
  "MIA": 6,
  "MIN": 6,
  "NE": 14,
  "NO": 11,
  "NYG": 11,
  "NYJ": 12,
  "PHI": 5,
  "PIT": 9,
  "SEA": 10,
  "SF": 9,
  "TB": 11,
  "TEN": 12,
  "WAS": 14
};

module.exports = { RAW, BYE_WEEKS };
