const RAW = [
  ["Ja'Marr Chase","WR","CIN",1.4],["Bijan Robinson","RB","ATL",2.3],
  ["Justin Jefferson","WR","MIN",3.1],["CeeDee Lamb","WR","DAL",4.2],
  ["Saquon Barkley","RB","PHI",5.5],["Jahmyr Gibbs","RB","DET",6.4],
  ["Christian McCaffrey","RB","SF",7.8],["Malik Nabers","WR","NYG",8.6],
  ["Amon-Ra St. Brown","WR","DET",9.4],["Puka Nacua","WR","LAR",10.3],
  ["Brian Thomas Jr.","WR","JAX",11.5],["Ashton Jeanty","RB","LV",12.6],
  ["Drake London","WR","ATL",13.4],["De'Von Achane","RB","MIA",14.5],
  ["Brock Bowers","TE","LV",15.2],["Nico Collins","WR","HOU",16.4],
  ["Garrett Wilson","WR","NYJ",17.5],["Derrick Henry","RB","BAL",18.8],
  ["Josh Jacobs","RB","GB",19.9],["Ladd McConkey","WR","LAC",20.7],
  ["Bucky Irving","RB","TB",21.6],["Tee Higgins","WR","CIN",22.4],
  ["A.J. Brown","WR","PHI",23.8],["Jonathan Taylor","RB","IND",24.5],
  ["Chase Brown","RB","CIN",25.6],["Kenneth Walker","RB","SEA",26.8],
  ["Marvin Harrison Jr.","WR","ARI",27.3],["Jaxon Smith-Njigba","WR","SEA",28.5],
  ["James Cook","RB","BUF",29.4],["DK Metcalf","WR","PIT",30.7],
  ["Davante Adams","WR","LAR",31.5],["Terry McLaurin","WR","WAS",32.8],
  ["Trey McBride","TE","ARI",33.4],["Joe Mixon","RB","HOU",34.6],
  ["DeVonta Smith","WR","PHI",35.5],["George Pickens","WR","DAL",36.7],
  ["Kyren Williams","RB","LAR",37.4],["Mike Evans","WR","TB",38.6],
  ["Jayden Daniels","QB","WAS",39.2],["Jalen Hurts","QB","PHI",40.5],
  ["Josh Allen","QB","BUF",41.3],["Lamar Jackson","QB","BAL",42.8],
  ["Sam LaPorta","TE","DET",43.4],["Jaylen Waddle","WR","DEN",44.6],
  ["Calvin Ridley","WR","TEN",45.8],["Rashee Rice","WR","KC",46.5],
  ["DJ Moore","WR","BUF",47.4],["Tetairoa McMillan","WR","CAR",48.7],
  ["Travis Etienne","RB","JAX",49.6],["Zach Charbonnet","RB","SEA",50.8],
  ["Tony Pollard","RB","TEN",51.5],["Jordan Love","QB","GB",52.4],
  ["Patrick Mahomes","QB","KC",53.6],["Bo Nix","QB","DEN",54.8],
  ["Courtland Sutton","WR","DEN",55.5],["Jameson Williams","WR","DET",56.7],
  ["Travis Kelce","TE","KC",57.4],["George Kittle","TE","SF",58.6],
  ["Chris Olave","WR","NO",59.5],["Stefon Diggs","WR","NE",60.8],
  ["Kaleb Johnson","RB","SEA",61.4],["Khalil Shakir","WR","BUF",63.5],
  ["Rome Odunze","WR","CHI",64.8],["Jordan Mason","RB","MIN",65.4],
  ["Tank Bigsby","RB","JAX",66.7],["Cooper Kupp","WR","SEA",67.5],
  ["Jakobi Meyers","WR","LV",68.8],["Caleb Williams","QB","CHI",69.4],
  ["Drake Maye","QB","NE",70.6],["Mark Andrews","TE","BAL",71.5],
  ["Quinshon Judkins","RB","CLE",72.8],["Tyreek Hill","WR","MIA",73.4],
  ["Tyler Lockett","WR","TEN",74.5],["Jaylen Warren","RB","PIT",75.7],
  ["Najee Harris","RB","LAC",76.4],["Ricky Pearsall","WR","SF",77.6],
  ["Tyler Warren","TE","IND",78.5],["David Montgomery","RB","DET",79.8],
  ["Jordan Addison","WR","MIN",80.4],["Tucker Kraft","TE","GB",82.5],
  ["Keon Coleman","WR","BUF",83.6],["Joe Burrow","QB","CIN",84.4],
  ["Baker Mayfield","QB","TB",85.5],["Justin Fields","QB","NYJ",86.8],
  ["Aaron Jones","RB","MIN",87.4],["Isiah Pacheco","RB","KC",88.6],
  ["Cam Skattebo","RB","NYG",89.5],["Xavier Worthy","WR","KC",90.7],
  ["Jerry Jeudy","WR","CLE",91.4],["Jauan Jennings","WR","SF",93.5],
  ["Hunter Henry","TE","NE",95.4],["David Njoku","TE","CLE",96.7],
  ["Adonai Mitchell","WR","IND",100.6],["Romeo Doubs","WR","GB",102.7],
  ["Jonnu Smith","TE","PIT",103.4],["Trey Benson","RB","ARI",105.5],
  ["Tyjae Spears","RB","TEN",107.4],["Jeremiyah Love","RB","ARI",109.5],
  ["Brock Purdy","QB","SF",110.7],["Will Shipley","RB","PHI",114.7],
  ["Cole Kmet","TE","CHI",116.6],["Josh Downs","WR","IND",120.6],
  ["Hollywood Brown","WR","KC",124.6],["Dallas Goedert","TE","PHI",132.6],
  ["Justin Herbert","QB","LAC",133.5],["Trevor Lawrence","QB","JAX",134.7],
  ["C.J. Stroud","QB","HOU",135.4],["Tua Tagovailoa","QB","MIA",136.6],
  ["Anthony Richardson","QB","IND",137.5],["Kyler Murray","QB","ARI",138.7],
  ["MarShawn Lloyd","RB","GB",140.6],["Jaylen Wright","RB","MIA",141.5],
  ["Kyle Pitts","TE","ATL",154.7],["Isaiah Likely","TE","BAL",155.4],
  ["Greg Dortch","WR","ARI",157.5],["Christian Watson","WR","GB",165.5],
];

// Bye weeks by team (updated with schedule)
const BYE_WEEKS = {
  ARI:11,ATL:12,BAL:14,BUF:12,CAR:11,CHI:7,CIN:12,CLE:10,
  DAL:7,DEN:9,DET:5,GB:12,HOU:14,IND:14,JAX:12,KC:10,
  LAC:5,LAR:6,LV:10,MIA:6,MIN:6,NE:14,NO:11,NYG:11,
  NYJ:12,PHI:5,PIT:9,SEA:10,SF:9,TB:11,TEN:12,WAS:14,
};

module.exports = { RAW, BYE_WEEKS };
