// AUTO-GENERATED — do not edit manually
// Updated: 2026-07-27 via fantasypoints.com Best Ball ADP (Underdog)
// Re-run: node scripts/update-adp.js
const RAW = [
  ["Jahmyr Gibbs","RB","DET",1.1],["Bijan Robinson","RB","ATL",2],["Ja'Marr Chase","WR","CIN",3.1],
  ["Puka Nacua","WR","LAR",4],["Jaxon Smith-Njigba","WR","SEA",5.4],["Christian McCaffrey","RB","SF",6.4],
  ["Amon-Ra St. Brown","WR","DET",7.2],["Jonathan Taylor","RB","IND",7.9],["CeeDee Lamb","WR","DAL",9.6],
  ["Justin Jefferson","WR","MIN",10],["Ashton Jeanty","RB","LV",11.2],["James Cook","RB","BUF",11.6],
  ["Saquon Barkley","RB","PHI",13.5],["Omarion Hampton","RB","LAC",14.5],["Kenneth Walker","RB","KC",15.7],
  ["Chase Brown","RB","CIN",16.3],["Devon Achane","RB","MIA",17.4],["Derrick Henry","RB","BAL",17.9],
  ["A.J. Brown","WR","NE",18.2],["Drake London","WR","ATL",19.9],["Brock Bowers","TE","LV",20.4],
  ["Nico Collins","WR","HOU",22.4],["George Pickens","WR","DAL",23.6],["Jeremiyah Love","RB","ARI",24.5],
  ["Rashee Rice","WR","KC",25],["DeVonta Smith","WR","PHI",26.3],["Breece Hall","RB","NYJ",28.4],
  ["Trey McBride","TE","ARI",28.7],["Chris Olave","WR","NO",29.8],["Zay Flowers","WR","BAL",30.3],
  ["Kyren Williams","RB","LAR",31.6],["Emeka Egbuka","WR","TB",32.2],["Tee Higgins","WR","CIN",33.2],
  ["Malik Nabers","WR","NYG",34.8],["Ladd McConkey","WR","LAC",34.8],["Josh Allen","QB","BUF",35.5],
  ["Javonte Williams","RB","DAL",36],["Travis Etienne Jr.","RB","NO",37.8],["Tetairoa McMillan","WR","CAR",38.9],
  ["Garrett Wilson","WR","NYJ",39.9],["Josh Jacobs","RB","GB",40.5],["Jaylen Waddle","WR","DEN",41.7],
  ["Cam Skattebo","RB","NYG",43.7],["Terry McLaurin","WR","WAS",43.8],["Luther Burden","WR","CHI",45],
  ["Mike Evans","WR","SF",46],["Colston Loveland","TE","CHI",46.9],["David Montgomery","RB","HOU",48.2],
  ["Davante Adams","WR","LAR",49.9],["D'Andre Swift","RB","CHI",50.4],["Jameson Williams","WR","DET",50.7],
  ["TreVeyon Henderson","RB","NE",52.5],["Quinshon Judkins","RB","CLE",53.6],["Bhayshul Tuten","RB","JAX",53.9],
  ["Mar'Keise 'Bucky' Irving","RB","TB",55.1],["Lamar Jackson","QB","BAL",55.6],["D.J. Moore","WR","BUF",56.5],
  ["Christian Watson","WR","GB",57],["Carnell Tate","WR","TEN",58.5],["Rome Odunze","WR","CHI",60.1],
  ["Brian Thomas","WR","JAX",61.4],["Jadarian Price","RB","SEA",62.4],["Jordyn Tyson","WR","NO",63.5],
  ["Tyler Warren","TE","IND",64.5],["Drake Maye","QB","NE",66.2],["Jayden Daniels","QB","WAS",67],
  ["Parker Washington","WR","JAX",67],["Joe Burrow","QB","CIN",68],["Marvin Harrison Jr.","WR","ARI",68],
  ["Caleb Williams","QB","CHI",71.7],["Jalen Hurts","QB","PHI",71.8],["Tony Pollard","RB","TEN",72.3],
  ["Makai Lemon","WR","PHI",73],["Jaylen Warren","RB","PIT",73.3],["Quentin Johnston","WR","LAC",74.4],
  ["Rhamondre Stevenson","RB","NE",76.3],["DK Metcalf","WR","PIT",77],["Chuba Hubbard","RB","CAR",79.2],
  ["Alec Pierce","WR","IND",80.2],["Dak Prescott","QB","DAL",80.8],["Justin Herbert","QB","LAC",81.8],
  ["Tucker Kraft","TE","GB",82.5],["Courtland Sutton","WR","DEN",83.2],["Jayden Reed","WR","GB",84.3],
  ["Trevor Lawrence","QB","JAX",85.5],["RJ Harvey","RB","DEN",85.9],["Rico Dowdle","RB","PIT",87],
  ["Chris Godwin","WR","TB",87.6],["Jordan Addison","WR","MIN",88.9],["Josh Downs","WR","IND",90.4],
  ["Blake Corum","RB","LAR",91.3],["Patrick Mahomes","QB","KC",93.1],["Kyle Monangai","RB","CHI",93.7],
  ["Sam LaPorta","TE","DET",94.6],["Xavier Worthy","WR","KC",94.8],["Brock Purdy","QB","SF",95.9],
  ["Ricky Pearsall","WR","SF",96.5],["Jonathon Brooks","RB","CAR",98.3],["J.K. Dobbins","RB","DEN",98.7],
  ["Michael Pittman Jr.","WR","PIT",99.6],["Michael Wilson","WR","ARI",101.3],["Jaxson Dart","QB","NYG",101.9],
  ["Harold Fannin","TE","CLE",104.3],["Kyle Pitts","TE","ATL",105.1],["Matthew Stafford","QB","LAR",106.2],
  ["Jakobi Meyers","WR","JAX",107.1],["Bo Nix","QB","DEN",107.2],["Kenneth Gainwell","RB","TB",107.7],
  ["Rachaad White","RB","WAS",108.3],["Jared Goff","QB","DET",109.5],["Matthew Golden","WR","GB",110.6],
  ["Kyler Murray","QB","MIN",111.4],["Jordan Love","QB","GB",112.7],["George Kittle","TE","SF",113.8],
  ["Wan'Dale Robinson","WR","TEN",113.9],["Jordan Mason","RB","MIN",113.9],["Romeo Doubs","WR","NE",116.8],
  ["Baker Mayfield","QB","TB",118.2],["KC Concepcion","WR","CLE",118.5],["Aaron Jones","RB","MIN",120.9],
  ["Jacory Croskey-Merritt","RB","WAS",121.3],["Travis Kelce","TE","KC",121.7],["Tyler Shough","QB","NO",123.4],
  ["Jayden Higgins","WR","HOU",124.3],["Mark Andrews","TE","BAL",125.7],["Khalil Shakir","WR","BUF",126.7],
  ["Chris Rodriguez Jr.","RB","JAX",127.7],["Dalton Kincaid","TE","BUF",127.8],["Isaiah Likely","TE","NYG",129.2],
  ["Jake Ferguson","TE","DAL",130.4],["Jalen Coker","WR","CAR",131.1],["Rashid Shaheed","WR","SEA",131.2],
  ["Stefon Diggs","WR","FA",133.5],["Tyrone Tracy","RB","NYG",133.5],["Malik Willis","QB","MIA",134.7],
  ["Dallas Goedert","TE","PHI",134.9],["Keaton Mitchell","RB","LAC",137],["Cameron Ward","QB","TEN",139.9],
  ["Chig Okonkwo","TE","WAS",140.5],["Sam Darnold","QB","SEA",140.8],["Travis Hunter","WR","JAX",141.4],
  ["Woody Marks","RB","HOU",141.9],["CJ Stroud","QB","HOU",142.9],["Omar Cooper","WR","NYJ",143.7],
  ["Jalen McMillan","WR","TB",145.1],["Daniel Jones","QB","IND",146.6],["Jalen Nailor","WR","LV",147.6],
  ["Isiah Pacheco","RB","DET",149.3],["Oronde Gadsden","TE","LAC",149.4],["Brenton Strange","TE","JAX",150.7],
  ["Hunter Henry","TE","NE",151.4],["Tyjae Spears","RB","TEN",152.7],["Jauan Jennings","WR","MIN",152.8],
  ["Tre Tucker","WR","LV",153.4],["Denzel Boston","WR","CLE",155.1],["Jonah Coleman","RB","DEN",156.3],
  ["Juwan Johnson","TE","NO",156.4],["Bryce Young","QB","CAR",158.5],["Ryan Flournoy","WR","DAL",160.4],
  ["Kenyon Sadiq","TE","NYJ",161.1],["Zach Charbonnet","RB","SEA",161.5],["Tyler Allgeier","RB","ARI",162.4],
  ["Tank Bigsby","RB","PHI",163.1],["Deebo Samuel","WR","FA",164.2],["Alvin Kamara","RB","NO",166.2],
  ["Tre Harris","WR","LAC",166.3],["Isaac TeSlaa","WR","DET",167],["Dalton Schultz","TE","HOU",167.9],
  ["T.J. Hockenson","TE","MIN",169.6],["De'Zhaun Stribling","WR","SF",171.9],["Adonai Mitchell","WR","NYJ",172],
  ["Brian Robinson","RB","ATL",172.5],["Dylan Sampson","RB","CLE",172.6],["AJ Barner","TE","SEA",174.2],
  ["Antonio Williams","WR","WAS",175.1],["Fernando Mendoza","QB","LV",176.2],["Aaron Rodgers","QB","PIT",177.7],
  ["Greg Dulcich","TE","MIA",178.1],["Jerry Jeudy","WR","CLE",179.1],["Gunnar Helm","TE","TEN",180.8],
  ["Zachariah Branch","WR","ATL",182.2],["Malik Washington","WR","MIA",183.5],["Geno Smith","QB","NYJ",184.9],
  ["Sean Tucker","RB","TB",185.4],["Cade Otton","TE","TB",186.4],["Terrance Ferguson","TE","LAR",187.3],
  ["Germie Bernard","WR","PIT",187.7],["Calvin Ridley","WR","TEN",188.3],["Dontayvion Wicks","WR","PHI",189.4],
  ["Ray Davis","RB","BUF",190.9],["Emmett Johnson","RB","KC",191.1],["Pat Freiermuth","TE","PIT",192.6],
  ["Tank Dell","WR","HOU",193.2],["Jaydon Blue","RB","DAL",194.4],["Jacoby Brissett","QB","ARI",196.9],
  ["Darnell Mooney","WR","NYG",197.2],["Marshawn Lloyd","RB","GB",197.6],["Mike Washington","RB","LV",198.5],
  ["Ted Hurst","WR","TB",202.2],["Kaytron Allen","RB","WAS",202.9],["Pat Bryant","WR","DEN",203.8],
  ["Mike Gesicki","TE","CIN",204.4],["Elijah Sarratt","WR","BAL",205.1],["Tua Tagovailoa","QB","ATL",206.6],
  ["Cooper Kupp","WR","SEA",207.5],["Braelon Allen","RB","NYJ",207.8],["Keon Coleman","WR","BUF",208],
  ["Rashod Bateman","WR","BAL",209.1],["Nicholas Singleton","RB","TEN",209.2],["Eli Stowers","TE","PHI",209.6],
  ["Jaylin Noel","WR","HOU",209.7],["Jordan James","RB","SF",210],["Tyquan Thornton","WR","KC",210.1],
  ["Colby Parkinson","TE","LAR",210.5],["Kayshon Boutte","WR","NE",211.5],["George Holani","RB","SEA",211.9],
  ["Keenan Allen","WR","FA",212.5],["David Njoku","TE","LAC",212.6],["Evan Engram","TE","DEN",212.7],
  ["Troy Franklin","WR","DEN",213.2],["Demond Claiborne","RB","MIN",213.3],["Chris Brazzell","WR","CAR",213.4],
  ["Malachi Fields","WR","NYG",213.7],["Shedeur Sanders","QB","CLE",213.7],["Christian Kirk","WR","SF",213.9],
  ["Brandon Aiyuk","WR","SF",213.9],["Justice Hill","RB","BAL",214.2],["Kimani Vidal","RB","LAC",214.4],
  ["Kaelon Black","RB","SF",214.5],["Darnell Washington","TE","PIT",214.6],["James Conner","RB","ARI",214.8],
  ["Tory Horton","WR","SEA",214.8],["Chris Bell","WR","MIA",214.8],["Michael Penix Jr.","QB","ATL",214.9],
  ["Michael Mayer","TE","LV",215],["Andrei Iosivas","WR","CIN",215],["Devaughn Vele","WR","NO",215],
  ["Jack Bech","WR","LV",215.1],["Kirk Cousins","QB","LV",215.2],["Deshaun Watson","QB","CLE",215.2],
  ["DJ Giddens","RB","IND",215.2],["Tyreek Hill","WR","FA",215.3],["Jalen Tolbert","WR","MIA",215.3],
  ["Ja'Kobi Lane","WR","BAL",215.3],["Samaje Perine","RB","CIN",215.4],["Theo Johnson","TE","NYG",215.4],
  ["Jake Tonges","TE","SF",215.4],["Skyler Bell","WR","BUF",215.4],["Caleb Douglas","WR","MIA",215.4],
  ["Darius Slayton","WR","NYG",215.6],["Jaylen Wright","RB","MIA",215.6],["Isaiah Davis","RB","NYJ",215.6],
  ["Zavion Thomas","WR","CHI",215.6],["Dawson Knox","TE","BUF",215.7],["Charlie Kolar","TE","LAC",215.7],
  ["Emanuel Wilson","RB","SEA",215.7],["Ja'Tavion Sanders","TE","CAR",215.7],["Carson Beck","QB","ARI",215.7],
  ["Erick All","TE","CIN",215.7],["LeQuint Allen","RB","JAX",215.7],["Chimere Dike","WR","TEN",215.7],
  ["Ty Johnson","RB","BUF",215.8],["Darren Waller","TE","FA",215.9],["Kendrick Bourne","WR","ARI",215.9],
  ["Hollywood Brown","WR","PHI",215.9],["Najee Harris","RB","FA",215.9],["Cole Kmet","TE","CHI",215.9],
  ["Justin Fields","QB","KC",215.9],["Treylon Burks","WR","WAS",215.9],["Marvin Mims","WR","DEN",215.9],
  ["Christopher Brooks","RB","GB",215.9],["Malik Davis","RB","DAL",215.9],["KaVontae Turpin","WR","DAL",215.9],
  ["Anthony Richardson","QB","IND",215.9],["Trey Benson","RB","ARI",215.9],["Emari Demercado","RB","KC",215.9],
  ["J.J. McCarthy","QB","MIN",215.9],["Devontez Walker","WR","BAL",215.9],["Xavier Legette","WR","CAR",215.9],
  ["Kyle Williams","WR","NE",215.9],["Tez Johnson","WR","TB",215.9],["Ollie Gordon","RB","MIA",215.9],
  ["Mason Taylor","TE","NYJ",215.9],["Elic Ayomanor","WR","TEN",215.9],["Oscar Delp","TE","NO",215.9],
  ["Elijah Arroyo","TE","SEA",215.9],["Isaiah Bond","WR","CLE",215.9],["Savion Williams","WR","GB",215.9],
  ["Adam Randall","WR","BAL",215.9],["Brenen Thompson","WR","LAC",215.9],["Justin Joly","TE","DEN",215.9],
  ["Bryce Lance","WR","NO",215.9],["Eli Raridon","TE","NE",215.9],["Cyrus Allen","WR","KC",215.9],
  ["Joe Flacco","QB","CIN",216],["Marcedes Lewis","TE","FA",216],["Tyrod Taylor","QB","GB",216],
  ["Russell Wilson","QB","FA",216],["Zach Ertz","TE","FA",216],["Teddy Bridgewater","QB","DET",216],
  ["Jameis Winston","QB","NYG",216],["Marcus Mariota","QB","WAS",216],["Mitchell Trubisky","QB","TEN",216],
  ["Kareem Hunt","RB","FA",216],["Jonnu Smith","TE","FA",216],["Nick Mullens","QB","JAX",216],
  ["Nick Chubb","RB","HOU",216],["Tyler Conklin","TE","DET",216],["Gardner Minshew II","QB","ARI",216],
  ["Devin Singletary","RB","NYG",216],["Jarrett Stidham","QB","DEN",216],["Jake Browning","QB","TB",216],
  ["Ashton Dulin","WR","IND",216],["Nick Westbrook-Ikhine","WR","IND",216],["Noah Gray","TE","KC",216],
  ["AJ Dillon","RB","CAR",216],["Trey Lance","QB","LAC",216],["Mac Jones","QB","SF",216],
  ["Kenny Pickett","QB","CAR",216],["Davis Mills","QB","HOU",216],["Tommy Tremble","TE","CAR",216],
  ["Jahan Dotson","WR","ATL",216],["John Metchie","WR","CAR",216],["Theo Wease","WR","MIA",216],
  ["Jerome Ford","RB","WAS",216],["Julius Chestnut","RB","TEN",216],["Tanner McKee","QB","PHI",216],
  ["Luke Musgrave","TE","GB",216],["Tyson Bagent","QB","CHI",216],["Hunter Luepke","RB","DAL",216],
  ["Elijah Higgins","TE","ARI",216],["Tommy DeVito","QB","NE",216],["Ben Sinnott","TE","WAS",216],
  ["Jarquez Hunter","RB","LAR",216],["Jawhar Jordan","RB","HOU",216],["Joe Milton","QB","DAL",216],
  ["Isaac Guerendo","RB","SF",216],["Will Shipley","RB","PHI",216],["Jordan Whittington","WR","LAR",216],
  ["Mitchell Evans","TE","CAR",216],["Will Howard","QB","PIT",216],["Devin Neal","RB","NO",216],
  ["Brashard Smith","RB","KC",216],["Trevor Etienne","RB","CAR",216],["Tahj Brooks","RB","CIN",216],
  ["Phil Mafah","RB","DAL",216],["Jackson Hawes","TE","BUF",216],["Damien Martinez","RB","GB",216],
  ["Kaleb Johnson","RB","PIT",216],["Quinn Ewers","QB","MIA",216],["J'Mari Taylor","RB","JAX",216],
  ["Ty Simpson","QB","LAR",216],["Max Klare","TE","LAR",216],["Jack Endries","TE","CIN",216],
  ["Jam Miller","RB","NE",216],["Taylen Green","QB","CLE",216],["Seth McGowan","RB","IND",216],
  ["Nate Boerkircher","TE","JAX",216],["Eli Heidenreich","RB","PIT",216],["Matt Hibner","TE","BAL",216],
  ["Cade Klubnik","QB","NYJ",216],["Michael Trigg","TE","DAL",216],["Gregory Desrosiers","RB","LAC",216],
];

const BYE_WEEKS = {
  "ARI": 11,
  "ATL": 12,
  "BAL": 14,
  "BUF": 12,
  "CAR": 11,
  "CHI": 7,
  "CIN": 12,
  "CLE": 10,
  "DAL": 7,
  "DEN": 9,
  "DET": 5,
  "GB": 12,
  "HOU": 14,
  "IND": 14,
  "JAX": 12,
  "KC": 10,
  "LAC": 5,
  "LAR": 6,
  "LV": 10,
  "MIA": 6,
  "MIN": 6,
  "NE": 14,
  "NO": 11,
  "NYG": 11,
  "NYJ": 12,
  "PHI": 5,
  "PIT": 9,
  "SEA": 10,
  "SF": 9,
  "TB": 11,
  "TEN": 12,
  "WAS": 14
};

module.exports = { RAW, BYE_WEEKS };
